osx_image: xcode8.1
language: objective-c
branches:
    only:
        - develop
        - master
notification:
    email: true
before_install:
    - gem install bundler
    - brew update
    - bundle install && brew bundle
script:
    - bundle exec fastlane tests
